### ISSUE TITLE
Feedback for “Billing”

### ISSUE THREAD

**Issue by Lmmmmmm-bb** [zeabur/docs#12]
There is no documentation on billing, so I would like to ask about the current billing rate and how much it costs.

https://docs.zeabur.com/manage/metric#billing

**Comment by MichaelYuhe** [comment]
Sorry, we are now promote our products for free, so the documentation is not ready yet. I forgot to explain this in the document. I'll let you know when we start charging.

**Comment by Lmmmmmm-bb** [comment]
> Sorry, we are now promote our products for free, so the documentation is not ready yet. I forgot to explain this in the document. I'll let you know when we start charging.

Thanks, I have experienced your platform and feel very well!
