### ISSUE TITLE
Errors occurred while creating new envirnment

### ISSUE THREAD

**Issue by yorelog** [zeabur/docs#20]
![fd710e507f5451d8059115fc11bb2ef](https://user-images.githubusercontent.com/6009347/211187854-74d53047-caa0-4155-9a78-e0c117743021.png)

**Comment by MichaelYuhe** [comment]
We are very sorry for this, and we are trying to fix this problem.
 Would you like to join our discord or telegram user group so we can have a further discussion about this?
Our Discord Link: https://discord.gg/5fMbmtbh
Our Telegram Link: https://t.me/zeabur_app
