### ISSUE TITLE
the user login status menu may makes user confusing

### ISSUE THREAD

**Issue by yorelog** [zeabur/docs#21]
![image](https://user-images.githubusercontent.com/6009347/211187951-43956c3d-f688-42ce-8deb-a1f67c063796.png)

**Comment by MichaelYuhe** [comment]
Thanks for feedback, I'll improve this soon.

**Comment by MichaelYuhe** [comment]
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/63531512/211238341-dbd92d49-44f7-4da7-a53c-5f66c0f8259e.png">
Fixed.
