### ISSUE TITLE
自定义域名问题

### ISSUE THREAD

**Issue by GinMiraing** [zeabur/docs#30]
请问下域名的 DNS 记录应该指向哪里？

![](https://article.biliimg.com/bfs/article/58f85d231d74d96ac62324fd923de61a2ae930d9.png)

**Comment by MichaelYuhe** [comment]
您好，对文档给您带来的困扰深感抱歉，我们更新了域名相关的文档，希望能解答您的疑惑。
https://docs.zeabur.com/zh-CN/deploy/domain-binding
若仍有其他问题，欢迎反馈，我们将会持续跟进 😊
