### ISSUE TITLE
默认build命令之后部署根目录下的/dist文件夹吗

### ISSUE THREAD

**Issue by Createitv** [zeabur/docs#41]
![image](https://user-images.githubusercontent.com/39019652/222193496-8b91218f-84c6-46ce-99a2-d6e882438dee.png)

**Comment by yuaanlin** [comment]
你好 @Createitv ，请问你的项目是什么类型的服务呢？

例如使用了什么框架，或是基于什么编程语言 ... 

或是如果你部署的项目是开源的，可以直接提供我们仓库地址。

请提供我们更多信息，让我们协助你解决问题！

**Comment by Createitv** [comment]
> 你好 @Createitv ，请问你的项目是什么类型的服务呢？
> 
> 例如使用了什么框架，或是基于什么编程语言 ...
> 
> 或是如果你部署的项目是开源的，可以直接提供我们仓库地址。
> 
> 请提供我们更多信息，让我们协助你解决问题！

我使用的VitePress框架部署文档。[仓库地址](https://github.com/Createitv/panghuang-indie-hacker)

**Comment by yuaanlin** [comment]
@Createitv 谢谢你提供的信息！

Zeabur 目前还没有让用户可以自行配置构建产物路径的能力，但我们刚刚为 Vitepress 框架的官方推荐配置加入了支持。
当您部署 Vitepress 项目到 Zeabur 后， Zeabur 会使用 `build` 或 `docs:build` 命令进行构建，然后将 `docs/.vitepress/dist` 目录下的文件以静态文件的方式部署。

请您协助我们修改配置后重新部署一次，谢谢！

**Comment by Createitv** [comment]
@yuaanlin 
搞定，响应真快。定价策略可以出来了。前端用起来还是挺香的
![image](https://user-images.githubusercontent.com/39019652/222343470-24025cd9-22ee-42c7-9d3c-266856746f34.png)

**Comment by MichaelYuhe** [comment]
> @yuaanlin 搞定，响应真快。定价策略可以出来了。前端用起来还是挺香的 ![image](https://user-images.githubusercontent.com/39019652/222343470-24025cd9-22ee-42c7-9d3c-266856746f34.png)

[定价策略](https://zeabur.com/zh-CN/pricing) 已经上线啦，下阶段就会推出具体的服务
