### ISSUE TITLE
无法获取真实IP

### ISSUE THREAD

**Issue by DearXuan7392** [zeabur/docs#43]
我用Express搭建了一个服务，并尝试用"request.ip"来获取来源ip，但是获取到的是内网ip:"10.*.*.*"

![image](https://user-images.githubusercontent.com/48397227/223447922-fbdc5c52-2c42-4516-8569-38e4855679bd.png)

**Comment by yuaanlin** [comment]
你好，这是因为进入 Zeabur 的请求会经过内部的转发才抵达你部署的服务内，所以现阶段还没有办法从服务内获取用户的真实 IP。

在未来的计划中，我们会在 request header 中注入 `x-forwarded-for` 字段 (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) ，让用户部署的服务可以获取真实 ip。

**Comment by yuaanlin** [comment]
@DearXuan7392 抱歉久等了，您现在可以在服务中通过 `x-forwarded-for` 或 `x-real-ip` 取得用户的真实 ip 了。
