### ISSUE TITLE
"Runtime logs" panel renders HTML unexpectly

### ISSUE THREAD

**Issue by imaegoo** [zeabur/docs#47]
If log contains HTML tags, it will render in the "Runtime logs" panel. May cause XSS

### Expected

Show original HTML codes in runtime log.

### Screenshot

![20230315123547](https://user-images.githubusercontent.com/20182252/225208023-56a7f824-7da0-4027-8f89-f70f89aee812.png)

**Comment by MichaelYuhe** [comment]
Thanks for feedback, it's because I use a lib to convert ansi code, I will fix it now.

**Comment by MichaelYuhe** [comment]
It should be fixed now, I'll convert ansi code in another way in our new dash.
