### ISSUE TITLE
Feedback for “快速开始”

### ISSUE THREAD

**Issue by Eison9** [zeabur/docs#49]
![image](https://user-images.githubusercontent.com/43535121/226292113-9344c41a-4d05-4210-80b8-5f984fa462de.png)
新建了一个项目，把project删掉后就这样了，,,,我以为是COOKIE问题，清楚之后发现是账号都出问题。整个账号就尬在这里了

**Comment by MichaelYuhe** [comment]
很抱歉对您带来的困扰，该问题已经修复～
