### ISSUE TITLE
平台目前自定义域名不支持ssl

### ISSUE THREAD

**Issue by owoneko** [zeabur/docs#54]
我部署了一个web应用，在绑定自定义域名时发现证书不匹配，希望官方添加ssl证书颁发功能。

**Comment by yuaanlin** [comment]
您好，目前 Zeabur 已经有自带 SSL 证书颁发功能，您只要将域名绑定到您的服务以后平台就会自动绑定（一般需要 30 秒至一分钟的时间）。

若您的服务访问时发现证书不匹配，请您回到 Zeabur 后台查看域名当前的状态是否为 `PROVISIONED`。

同时，若您的域名曾经绑定在其他平台上，您的浏览器可能还留有该域名的证书缓存，这也会导致您访问时短暂发生证书不匹配的情况。

**Comment by yuaanlin** [comment]
> 依然无法使用ssl～

方便提供下域名吗

**Comment by yuaanlin** [comment]
> https://chatgpt.aitoolshub.cn/

@wuyongwen 刚刚排查了一下，确实在证书申请的部分发生了一个问题，目前已经可以正常访问啦～

**Comment by owoneko** [comment]
已解决
