### ISSUE TITLE
Feedback for “快速开始”

### ISSUE THREAD

**Issue by VMTask** [zeabur/docs#61]
Can Zeabur support SFTP?

**Comment by VMTask** [comment]
How to backup files from the container?

**Comment by yuaanlin** [comment]
> Can Zeabur support SFTP?

For services deployed from your source code on Zeabur, the only protocol supported is HTTPS.

> How to backup files from the container?

You should not save any data or files in the container because you need to keep it stateless. In other words, once you push a new deployment, all data in your container will loss.

**Comment by yuaanlin** [comment]
If you have any further question, please feel free to discuss on [GitHub Discussion](https://github.com/orgs/zeabur/discussions) or our [Discord Server](https://discord.gg/DrdGCvXEyY)!
