### ISSUE TITLE
收费问题：目前是根据内存和vcpu使用量收费，带宽免费且不设限制吗？

### ISSUE THREAD

**Issue by xiguazhiPrince** [zeabur/docs#64]
如题

**Comment by yuaanlin** [comment]
您好，带宽会有限制并且未来可能考虑按量计费，至于具体上限及定价目前还在讨论中，谢谢！

**Comment by xiguazhiPrince** [comment]
> 您好，带宽会有限制并且未来可能考虑按量计费，至于具体上限及定价目前还在讨论中，谢谢！

明白，支持。不过在考虑按量计费的时候，可以考虑下恶意攻击导致用户费用损失的情况吗？不是每个开发者会考虑到这个问题和会做安全相关的防御机制，那么开发平台是否可以提供防御机制，不需要开发者做额外开发和配置，这样可以帮助减少用户的损失。

**Comment by yuaanlin** [comment]
> 明白，支持。不过在考虑按量计费的时候，可以考虑下恶意攻击导致用户费用损失的情况吗？不是每个开发者会考虑到这个问题和会做安全相关的防御机制，那么开发平台是否可以提供防御机制，不需要开发者做额外开发和配置，这样可以帮助减少用户的损失。

这个是一定的，我们目前也在调研如何结合 CloudFlare 提供我们全球用户高速、稳定且安全的网络服务。
